TRAIN_IMAGES_PATH = r'D:\\backup\\TESIS\DATASETS\train2014\\'
VAL_IMAGES_PATH = r'D:\\backup\\TESIS\DATASETS\val2014\\'
TEST_IMAGES_PATH = r'D:\\backup\\TESIS\DATASETS\test2014\\'

TRAIN_CAPTIONS_PATH = r'D:\\backup\\TESIS\DATASETS\captions_train2014.json'
VAL_CAPTIONS_PATH = r'D:\\backup\\TESIS\DATASETS\captions_val2014.json'
TEST_CAPTIONS_PATH = r'D:\\backup\\TESIS\DATASETS\captions_test2014.json'

VLAD_DESCRIPTORS_TRAIN_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\VLAD\TRAIN\\'
VLAD_DESCRIPTORS_VAL_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\VLAD\VAL\\'
VLAD_DESCRIPTORS_TEST_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\VLAD\TEST\\'

VLAD_PCA_DESCRIPTORS_TRAIN_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\VLAD_PCA\TRAIN\\'
VLAD_PCA_DESCRIPTORS_VAL_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\VLAD_PCA\VAL\\'
VLAD_PCA_DESCRIPTORS_TEST_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\VLAD_PCA\TEST\\'

CNN_DESCRIPTORS_TRAIN_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\CNN\TRAIN\\'
CNN_DESCRIPTORS_VAL_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\CNN\VAL\\'
CNN_DESCRIPTORS_TEST_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\CNN\TEST\\'

PCA_MODEL = r'D:\\backup\\TESIS\MODEL\pca_cnn.pickle'
PCA_MODEL_VLAD = r'D:\\backup\\TESIS\MODEL\pca_vlad.pickle'
CNN_PCA_DESCRIPTORS_TRAIN_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\CNN_PCA\TRAIN\\'
CNN_PCA_DESCRIPTORS_VAL_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\CNN_PCA\VAL\\'
CNN_PCA_DESCRIPTORS_TEST_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\CNN_PCA\TEST\\'

BIGRAM_MODEL = r'D:\\backup\\TESIS\MODEL\bigram.pickle'
REDUCED_BIGRAM_MODEL = r'D:\\backup\\TESIS\MODEL\reduced_bigram.pickle'
TF_IDF_MODEL = r'D:\\backup\\TESIS\MODEL\tf_idf.pickle'
REDUCED_TF_IDF_MODEL = r'D:\\backup\\TESIS\MODEL\reduced_tf_idf.pickle'

TFIDF_DESCRIPTORS_TRAIN_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\TFIDF\TRAIN\\'
TFIDF_DESCRIPTORS_VAL_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\TFIDF\VAL\\'
TFIDF_DESCRIPTORS_TEST_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\TFIDF\TEST\\'

REDUCED_TFIDF_DESCRIPTORS_TRAIN_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\TFIDF_REDUCED\TRAIN\\'
REDUCED_TFIDF_DESCRIPTORS_VAL_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\TFIDF_REDUCED\VAL\\'
REDUCED_TFIDF_DESCRIPTORS_TEST_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\TFIDF_REDUCED\TEST\\'

W2V_DESCRIPTORS_TRAIN_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\WORD2VECT\TRAIN\\'
W2V_DESCRIPTORS_VAL_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\WORD2VECT\VAL\\'
W2V_DESCRIPTORS_TEST_PATH = r'D:\\backup\\TESIS\DESCRIPTORS\WORD2VECT\TEST\\'


TMP_PATH = r'D:\\backup\\TESIS\TMP\\'
#TMP contains files like the center of the clustering

USE_PCA = True
DIM = 128 #VLAD PAPER

CNN_TEST_INDEX = r'D:\\backup\\TESIS\MODEL\cnn_pca_test_index.pickle'
CNN_TEST_ORDER = r'D:\\backup\\TESIS\MODEL\cnn_pca_test_order.pickle'
CNN_VAL_INDEX = r'D:\\backup\\TESIS\MODEL\cnn_pca_val_index.pickle'
CNN_VAL_ORDER = r'D:\\backup\\TESIS\MODEL\cnn_pca_val_order.pickle'
CNN_TRAIN_INDEX = r'D:\\backup\\TESIS\MODEL\cnn_pca_train_index.pickle'
CNN_TRAIN_ORDER = r'D:\\backup\\TESIS\MODEL\cnn_pca_train_order.pickle'

VLAD_VAL_INDEX = r'D:\\backup\\TESIS\MODEL\vlad_pca_val_index.pickle'
VLAD_VAL_ORDER = r'D:\\backup\\TESIS\MODEL\vlad_pca_val_order.pickle'
VLAD_TRAIN_INDEX = r'D:\\backup\\TESIS\MODEL\vlad_pca_train_index.pickle'
VLAD_TRAIN_ORDER = r'D:\\backup\\TESIS\MODEL\vlad_pca_train_order.pickle'